### ISSUE TITLE
ArenaJoinEvent

### ISSUE THREAD

**Issue by ghost** [thebigsmileXD/gameapi#13]
Event when player joins the arena.
Possible noobish ways I found out to do this:
- LevelChangeEvent: checks if the level is an Arena, and if it is, add the player to the arena
- When the player runs /command join Arena
- Implement it in arena.php

**Comment by inxomnyaa** [comment]
It is not needed
https://github.com/thebigsmileXD/gameapi/blob/master/src/xenialdan/gameapi/Arena.php#L232
https://github.com/thebigsmileXD/gameapi/blob/master/src/xenialdan/gameapi/Arena.php#L169-L170

**Comment by inxomnyaa** [comment]
but maybe it will make things simpler for other plugins. But even if you need it, you could just create the event and call it in the function?

**Comment by ghost** [comment]
Seems fair..

**Comment by inxomnyaa** [comment]
I might include this in the next rewrite (if ever)
