### ISSUE TITLE
???

### ISSUE THREAD

**Issue by CarlosCraft1145** [thebigsmileXD/gameapi#5]
I'm trying to figure out how to use this plugin. It would be nice for a tutorial. 
 
     Thanks

**Comment by ghost** [comment]
@CarlosCraft1145 For an example, see [here](https://github.com/thebigsmileXD/Spleef)

**Comment by MalakasPlayzMC** [comment]
@thebigsmileXD can you release your gadgets plugin?

**Comment by GianisTsol** [comment]
google something before you ask..
