### ISSUE TITLE
Can I make TurfWars with this?

### ISSUE THREAD

**Issue by xXNiceYT** [thebigsmileXD/gameapi#7]

**Comment by dries-c** [comment]
Yeah, Why not lol

**Comment by xXNiceYT** [comment]
Do you use it @Driesboy for nether games xd bc u replied

**Comment by dries-c** [comment]
Nope, We use our own code base.

**Comment by xXNiceYT** [comment]
Do u know how to make 1 player per team :/ bc this plugin doesn’t have team that I don’t understand

**Comment by dries-c** [comment]
I have no idea. I never used this. I'm just watching this.

**Comment by DenielWorld** [comment]
This plugin really needs some examples

**Comment by inxomnyaa** [comment]
Just set team min/max players to 1. You can create anything, you just need some creativity

**Comment by inxomnyaa** [comment]
Also it is not a plugin, it is a virion. BedWars and Spleef exist as examples. I currently have no more time to code any extra examples or minigames, but someone made a great skywars with it recently

**Comment by DenielWorld** [comment]
Miswrote about the "plugin"
