### ISSUE TITLE
Virion does not load

### ISSUE THREAD

**Issue by ghost** [thebigsmileXD/gameapi#8]
Hello! SO, recently I started using the GAMEAPI. I installed xBedWars (by you) to look at some source code and learn new things. I tried to load it but got the error to use this plugin. I am running PocketMine - MP 3.9.5, PHP 7.2 Windows, and Windows 7. I installed this but it would not load. Please fix this. The version I am uing:

![llakas](https://user-images.githubusercontent.com/49820135/66703404-c79f6700-ed2b-11e9-8a26-c17a81521592.PNG)

**Comment by inxomnyaa** [comment]
I cannot fully see the error. Can you please send the console output/log?

Have you installed the apibossbar virion also? It is a dependency of gameapi, i cannot see it in your virion folder

**Comment by ghost** [comment]
It has no error.. It just does not load. And, yeah, I have the latest version from apibossbar from poggit. I'm using 3.9.7 and php 7.2 obviously. P.S. Sorry for the late reply, I get tons of emails so I was just scrolling down and saw the GH notification. Thanks!

**Comment by inxomnyaa** [comment]
Maybe the xbedwars release uses older versions to run, not sure though.

Do you have DEVirion installed? Do other virions load? Does not look like it from the screenshot.

There is also a little issue on API 3.9 due to plugin load order - you might need to add softdepend: DEVirion into plugin.yml to fix the load order causing crashes, blame dktapps

**Comment by ghost** [comment]
Yeah, I'll try that. I don't have DEVirion installed, never felt the need to have it somehow. I'll install it, add the dependency to the code, and test it again. I'll also try my best to fix stuff myself, but will inform you just in case you think I broke anything myself XD. 
GN/GM!

**Comment by inxomnyaa** [comment]
Closing as DEVirion is necessary to load virions when running from source
